### ISSUE TITLE
UITableView reloadData , keyboard dismiss

### ISSUE THREAD

**Issue by softknife** [ra1028/Former#107]
I have a TextView inside a UITableViewCell. The text inside the TextView can be edited right there in place.

The TextView grows and shrinks vertically depending on the number of lines the text contains. So far I haven't found a possibility to also let the row containing the TextView grow and shrink dynamically.

I find some solution at stackoverflow [](https://stackoverflow.com/questions/5344206/change-uitableview-row-height-without-dismissing-keyboard)

**Comment by ZacharyKhan** [comment]
This is a duplicate to #108, closing this issue. I'll leave #108 open and we can try to solve this there.
