### ISSUE TITLE
Can change style of UItableview

### ISSUE THREAD

**Issue by dlpigpen** [ra1028/Former#16]
I think we should put an option that we can change the style of the tableview and the tableview should be a var to easy to change value of the property.

**Comment by FredvanRijswijk** [comment]
Where to change the style of subheadings like Profile Image text and the gray tableview?

**Comment by arronhunt** [comment]
Going to bump this one because I think it's pretty important

**Comment by ZacharyKhan** [comment]
I'll update this ASAP. I agree, the `tableView` property of `FormViewController` shouldn't be marked as private if there's no solid reasoning.
