### ISSUE TITLE
Errore while hide/show dateRow

### ISSUE THREAD

**Issue by lucabecchetti** [ra1028/Former#18]
Hi, i have this code that works fine:

`private func switchInfomationSectionDate() {
        if moreInformationDate == true {
            former.insertUpdate(rowFormer: allDayRow!, below: moreDate!)
            former.insertUpdate(rowFormer: locationRow!, below: allDayRow!)
            former.insertUpdate(rowFormer: selectAddressRow!, below: locationRow!)
        } else {
            former.removeUpdate(rowFormers: [allDayRow!,locationRow!,selectAddressRow!],rowAnimation:.Top)
            eventDetails["date_start"]    = ""
            eventDetails["date_end"]      = ""
        }
}`

i i change one rowFormer, for example: selectAddressRow and i put a datePickerRow

`endRow = InlineDatePickerRowFormer<FormInlineDatePickerCell>() {
            $0.titleLabel.text = "Fine"
            $0.titleLabel.font = .boldSystemFontOfSize(15)
            $0.displayLabel.font = .systemFontOfSize(15)
            .displayTextFromDate(String.mediumDateShortTime)
}`

the row is correctly added, but when i call switchInfomationSectionDate again i obtain:

**\* Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'attempt to delete row 4 from section 2 which only contains 4 rows before the update'
**\* First throw call stack:

Only with this type of row, any ideas?

**Comment by brokeniceinteractive** [comment]
Nobody can help me???!

**Comment by frankl98** [comment]
Its an additional removed lines in func `private func removeRowFormers(rowFormers: [RowFormer]) -> [NSIndexPath] `

code must be changed to (look at the part that is commented out):
`    private func removeRowFormers(rowFormers: [RowFormer]) -> [NSIndexPath] {
        var removedCount = 0
        var removeIndexPaths = [NSIndexPath]()
        for (section, sectionFormer) in sectionFormers.enumerate() {
            for (row, rowFormer) in sectionFormer.rowFormers.enumerate() {
                if rowFormers.contains({ $0 === rowFormer }) {
                    removeIndexPaths.append(NSIndexPath(forRow: row, inSection: section))
                    sectionFormer.remove(rowFormers: [rowFormer])
                    /*
                    if let oldInlineRowFormer = (rowFormer as? InlineForm)?.inlineRowFormer {
                        removeIndexPaths.append(NSIndexPath(forRow: row + 1, inSection: section))
                        removeRowFormers([oldInlineRowFormer])
                        (inlineRowFormer as? InlineForm)?.editingDidEnd()
                        inlineRowFormer = nil
                    }
					 */
                    removedCount += 1
                    if removedCount >= rowFormers.count {
                        return removeIndexPaths
                    }
                }
            }
        }
        return removeIndexPaths
    }
`

**Comment by mdtempalert** [comment]
With Markdown. This patch works for me....

```
private func removeRowFormers(rowFormers: [RowFormer]) -> [NSIndexPath] {
        var removedCount = 0
        var removeIndexPaths = [NSIndexPath]()
        for (section, sectionFormer) in sectionFormers.enumerate() {
            for (row, rowFormer) in sectionFormer.rowFormers.enumerate() {
                if rowFormers.contains({ $0 === rowFormer }) {
                    removeIndexPaths.append(NSIndexPath(forRow: row, inSection: section))
                    sectionFormer.remove(rowFormers: [rowFormer])
//                    if let oldInlineRowFormer = (rowFormer as? InlineForm)?.inlineRowFormer {
//                        removeIndexPaths.append(NSIndexPath(forRow: row + 1, inSection: section))
//                        removeRowFormers([oldInlineRowFormer])
//                        (inlineRowFormer as? InlineForm)?.editingDidEnd()
//                        inlineRowFormer = nil
//                    }
                    removedCount += 1
                    if removedCount >= rowFormers.count {
                        return removeIndexPaths
                    }
                }
            }
        }
        return removeIndexPaths
    }
```

**Comment by frankl98** [comment]
@mdtempalert yes thats the solution!

**Comment by ZacharyKhan** [comment]
Closing, solution found.
