### ISSUE TITLE
compilation error on tags 1.3.0

### ISSUE THREAD

**Issue by mwapptest** [ra1028/Former#29]
Dear Sir, 
I just cloned git checkout tags/1.3.0 repo to run examples but I am getting 28 errors.

../Former/Former/Commons/FormerProtocol.swift:22:5: Expected declaration
../Former/Former/RowFormers/SliderRowFormer.swift:53:51: Expected expression in list of expressions

It must be something missing from my end. Can you please help me how to run the examples so I can learn this awesome lib?

**Comment by ZacharyKhan** [comment]
Can you close this issue? Update to version 1.6.0 and if the problem persists please open a new issue.
