### ISSUE TITLE
Segmented control with no selection

### ISSUE THREAD

**Issue by neilaur** [ra1028/Former#3]
Hi,

I want to show a segmented control without selection at creation (but not momentary). So, I've specified the attribute "selectedIndex" with the value "UISegmentedControlNoSegment". But, when i click for the first time on the segmented control, the app crash :

<code>
Former-Demo[45492:7325632] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 18446744073709551615 beyond bounds [0 .. 1]'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010cfd5f45 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010ef21deb objc_exception_throw + 48
	2   CoreFoundation                      0x000000010ceb99e4 -[__NSArrayM objectAtIndex:] + 212
	3   UIKit                               0x000000010dc33cc3 -[UISegmentedControl titleForSegmentAtIndex:] + 38
	4   Former                              0x000000010cd94e6b _TFC6Former18SegmentedRowFormerP33_5319F26570932CABE1649D3998AD612D12valueChangeduRdq_CSo15UITableViewCellq_S_20SegmentedFormableRow_fGS0_q__FCSo18UISegmentedControlT_ + 155
	5   Former                              0x000000010cd9512a _TToFC6Former18SegmentedRowFormerP33_5319F26570932CABE1649D3998AD612D12valueChangeduRdq_CSo15UITableViewCellq_S_20SegmentedFormableRow_fGS0_q__FCSo18UISegmentedControlT_ + 74
	6   UIKit                               0x000000010da1be91 -[UIApplication sendAction:to:from:forEvent:] + 92
	7   UIKit                               0x000000010db874d8 -[UIControl sendAction:to:forEvent:] + 67
	8   UIKit                               0x000000010db877a4 -[UIControl _sendActionsForEvents:withEvent:] + 311
	9   UIKit                               0x000000011bfc2791 -[UISegmentedControlAccessibility sendActionsForControlEvents:] + 39
	10  UIKit                               0x000000010dc34661 -[UISegmentedControl _setSelectedSegmentIndex:notify:animate:] + 690
	11  UIKit                               0x000000010dc36d35 -[UISegmentedControl touchesEnded:withEvent:] + 232
	12  UIKit                               0x000000010deed9ba _UIGestureRecognizerUpdate + 10279
	13  UIKit                               0x000000010da899c0 -[UIWindow _sendGesturesForEvent:] + 1137
	14  UIKit                               0x000000010da8abf6 -[UIWindow sendEvent:] + 849
	15  UIKit                               0x000000010da3a2fa -[UIApplication sendEvent:] + 263
	16  UIKit                               0x000000011bfbda29 -[UIApplicationAccessibility sendEvent:] + 77
	17  UIKit                               0x000000010da14abf _UIApplicationHandleEventQueue + 6844
	18  CoreFoundation                      0x000000010cf02011 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	19  CoreFoundation                      0x000000010cef7f3c __CFRunLoopDoSources0 + 556
	20  CoreFoundation                      0x000000010cef73f3 __CFRunLoopRun + 867
	21  CoreFoundation                      0x000000010cef6e08 CFRunLoopRunSpecific + 488
	22  GraphicsServices                    0x0000000112513ad2 GSEventRunModal + 161
	23  UIKit                               0x000000010da1a30d UIApplicationMain + 171
	24  Former-Demo                         0x000000010cbf9fad main + 109
	25  libdyld.dylib                       0x000000010fa2992d start + 1
	26  ???                                 0x0000000000000001 0x0 + 1
</code>

The crash can be simulated by adding the line <code>$0.selectedIndex = UISegmentedControlNoSegment</code> in the *ExampleViewController* (line 95). 

Could you have a look ?

Thx !

**Comment by ra1028** [comment]
Sorry for the late.
Fixed this at ver 1.2.0
