### ISSUE TITLE
`deinit` is newer called

### ISSUE THREAD

**Issue by vkosmirak** [ra1028/Former#32]
I subclass from `FormViewController` and configure `former`
When I pop this controller, `deinit` is not called

Is it some way to remove my `ViewController` from memory?

**Comment by vkosmirak** [comment]
I fixed it by calling next code in my `ViewController`

       override func viewWillDisappear(animated: Bool) {
           super.viewDidDisappear(animated)
        
           former = Former(tableView: UITableView.init())
      }

**Comment by ZacharyKhan** [comment]
Interesting, if you run into an error feel free to create a new PR. Closing due to lack of info/context on the issue.
