### ISSUE TITLE
inline pickers: setting of selected item not reflected in the picker (iOS 9.3)

### ISSUE THREAD

**Issue by frankl98** [ra1028/Former#33]
due to a missing reload of the picker, a setting of a selected item of the picker is not shown.

In file PickerRowFormer.swift the following line must be added after line `let picker = cell.formPickerView()`:

`picker.reloadAllComponents()`

**Comment by hajnalben** [comment]
+1

**Comment by mattjgalloway** [comment]
Yeh this happens for me also. Looks like #31 fixes this.

**Comment by benwalch** [comment]
31 fixes this for me too - any updates?

**Comment by ZacharyKhan** [comment]
I've submitted #64 which fixes this.
