### ISSUE TITLE
Double Text Field Cell Setup

### ISSUE THREAD

**Issue by justyn44** [ra1028/Former#34]
Hi there,

Relatively new to Swift and hoping someone may have had luck setting up the default ProfileFieldCell to accept two UITextFields as inputs. I saw the sample code provided, but was not able to seem to get it running.

Any help is greatly appreciated, thanks a bunch! :)

**Comment by ZacharyKhan** [comment]
Closing due to age. Try it out with version 1.6.0, there’s been a lot of updates to Former. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
