### ISSUE TITLE
removeUpdate crashes on inline rows

### ISSUE THREAD

**Issue by jennyh** [ra1028/Former#35]
It looks like removeRowFormer always marks the inline row for deletion, even when it is not active.

**Comment by ZacharyKhan** [comment]
Can you provide a code snippet so I can replicate this and fix it?

**Comment by jennyh** [comment]
No, Sorry,

This was over a year ago.  I stopped using Former and switched to Eureka.

**Comment by ZacharyKhan** [comment]
No problem, please close this issue so we can help those who still use Former 👍

**Comment by widemouthsupport** [comment]
Ok, especially as a duplicate if #49
