### ISSUE TITLE
How can I add a title on the left side like the one in your example to a ui switch

### ISSUE THREAD

**Issue by pprevalon** [ra1028/Former#36]

**Comment by mdtempalert** [comment]
Implement configure() and access the cell's formTitleLabel().

```
let row = SwitchRowFormer<FormSwitchCell>().configure { row in
    row.cell.formTitleLabel()!.text = "Switch on?"
}.onSwitchChanged { switched in
    print("Switch is " + (switched ? "on" : "off"))
}
```

**Comment by ZacharyKhan** [comment]
Closing due to age & inactivity. The demo example provided as a part of the `AddEventViewController` contains a switch with a label. Take a look at that and replicate what's done in the demo 👍
