### ISSUE TITLE
Swift 3.0

### ISSUE THREAD

**Issue by alpascual** [ra1028/Former#39]
Any chance to have a swift 3.0 version? Its a fantastic project!

**Comment by mattjgalloway** [comment]
Has anyone done a Swift 3 port yet? I started, but it's heavy going! I'm not that far off, but un-tested as yet, and I don't have full context of this project to know what things should look like under Swift 3.

**Comment by mattjgalloway** [comment]
My attempt is complete, and the demo works. #40 is the PR.

**Comment by bendash** [comment]
it would be awesome if the class access would be _open_ instead of _public_

**Comment by mattjgalloway** [comment]
Oh yes, that would be a good idea! I could do that when I get time, or I'm totally happy if someone else take it on.

**Comment by ra1028** [comment]
I released [swift3 supported version](https://github.com/ra1028/Former/tree/1.5.0) !
[Cocoapods](https://cocoapods.org/pods/Former)
Awesome job @mattjgalloway !
