### ISSUE TITLE
Serious performance issue, if open FormViewController for the first time.

### ISSUE THREAD

**Issue by KanybekMomukeyev** [ra1028/Former#41]
Hi @ra1028 , first of all, thanks  for good library, 
if i open formViewController for the first time, it's waiting for 2-3 seconds, and then opens view controller, can we avoid this issue?
I am developing app for ipad 2 generation, and this is really issue.

**Comment by ZacharyKhan** [comment]
Can you provide a code snippet? 2-3 seconds sounds like something else is going on here.
