### ISSUE TITLE
FormCell init(style: UITableViewCellStyle, reuseIdentifier: String?) not public

### ISSUE THREAD

**Issue by jennyinf** [ra1028/Former#43]
In swift 3, if I don't set this method to public, my custom (non xib) cell classes fall over when the rowFormer tries to create them

The same applies to FormHeaderFooterView

**Comment by stefanoa** [comment]
It is happening to me also, for the class FormCell.
When using it the app will crash with:

fatal error: use of unimplemented initializer 'init(style:reuseIdentifier:)' 

making the initialiser public fix the problem

**Comment by ZacharyKhan** [comment]
Can someone submit a PR with the fixes? Closing this issue as the solution has been found.
