### ISSUE TITLE
ViewFormer not showing correctly even in your example.

### ISSUE THREAD

**Issue by jechol** [ra1028/Former#5]
When I launch your example(with navigation controller just for clarity),
label and inline picker appears correctly.

But header view is not appears. It just take space.

Please see my screen shot.

![simulator screen shot dec 10 2015 5 36 45 pm](https://cloud.githubusercontent.com/assets/795125/11710800/32026912-9f65-11e5-8a6b-926e7d909e7d.png)

**Comment by jechol** [comment]
I found label.height = 0.

![formerex_xcworkspace](https://cloud.githubusercontent.com/assets/795125/11711455/e6ee1246-9f69-11e5-9dc9-0eedf167d767.png)

**Comment by jechol** [comment]
The example was wrong.

```
let header = LabelViewFormer<FormLabelHeaderView>() { view in
  view.titleLabel.text = "Label Header"
}
```

should be 

```
let header = LabelViewFormer<FormLabelHeaderView>()
header.text = "Label Header"
```

**Comment by ra1028** [comment]
@jechol 
Sorry, my example is wrong.
Correctly:
```
let header = LabelViewFormer<YourLabelHeaderView>()
header.text = "header"
```
or
```
let header = LabelViewFormer<YourLabelHeaderView>()
    .configure {
        $0.text = "header"
    }
```
