### ISSUE TITLE
Is there a way to detect if Section already contents RowFormer?

### ISSUE THREAD

**Issue by ADevelopStudio** [ra1028/Former#61]
Want to write login to add new RowFormer to section but need to check if there is already the same RowFormer.
kinda:
`        former.rowFormers.contains(where: <#T##(RowFormer) throws -> Bool#>)
`

**Comment by ADevelopStudio** [comment]
Already found out but a bit not secure way, sorry :)

`        let already = formers.contains(where: {$0.cell.titleLabel.text == self.NEEDED_FORMER_.cell.titleLabel.text})
`

**Comment by ZacharyKhan** [comment]
Can you close the issue if you've solved the problem?
