### ISSUE TITLE
Make custom expandable cell

### ISSUE THREAD

**Issue by Recouse** [ra1028/Former#70]
How to make a custom expandable cell? I tried:
```swift
    let passwordRow = CustomRowFormer<PasswordCell>().onSelected {
        $0.cell.passwordTextFieldsView.isHidden = false
        $0.update()
    }.dynamicRowHeight { tableView, indexPath -> CGFloat in
        return 50
    }
```
but it's not working.
Maybe someone already did this.

**Comment by ZacharyKhan** [comment]
Hello @Recouse, were you able to figure this out or did you still need help?

**Comment by Recouse** [comment]
@ZacharyKhan thanks, I think I already figured it out)
