### ISSUE TITLE
why do you forcefully stop editing when scrolling a table?

### ISSUE THREAD

**Issue by ilyatar** [ra1028/Former#74]
`public func scrollViewWillBeginDragging(_ scrollView: UIScrollView) {`
`       endEditing()`
`       onBeginDragging?(scrollView)`
`}`

**Comment by ZacharyKhan** [comment]
Hello @ilyatar, it's hard to provide help with little context. Please see our readme and submit a new issue following the template.

**Comment by ilyatar** [comment]
Thank you! This problem is no longer relevant
