### ISSUE TITLE
InlinePickerRowFormer: how to select a picker item programmatically

### ISSUE THREAD

**Issue by HaikuOezu** [ra1028/Former#81]
Hello,
I'm using former to allow the user to edit some data that is persisted locally, as such when initializing my view controller I need former rows to display the current values of the object
I have a InlinePickerRowFormer that allows the user to choose between multiple possible values, and I have noticed that no matter what I do it will always default to the first item in the picker, even if selectedRow is not 0

To set the current row I call
`$0.selectedRow`
Inside the `configure` block, but the row still defaults to the first option

I have tried using `update`, `cellUpdate` and even altering the `formDisplayLabel()` directly but nothing works, I can change the font of the display label but not the actual text.

I am positively stumped, I have no idea how to fix this... am I missing something?

**Comment by HaikuOezu** [comment]
After a bit more research it seems like there's no way to fix this without changing the behavior of former as indicated in issue #79

**Comment by B0Dim** [comment]
+1

**Comment by Daxito** [comment]
+1

**Comment by raulastu** [comment]
1

**Comment by ZacharyKhan** [comment]
This issue should be solved in #88 

If you are still having issues, please submit a new issue using the template below:

https://github.com/ra1028/Former/issues/new?template=bug_report.md
