### ISSUE TITLE
row.selectedRow stopped functioning in latest version.

### ISSUE THREAD

**Issue by raulastu** [ra1028/Former#83]
I have  1.6.1 and InlinePickerRowFormer row.selectedRow stopped working. It always selects the first element. It used to work in previous versions

**Comment by Voidozzer** [comment]
Same problem here

**Comment by shtnkgm** [comment]
I have the same problem
Former v1.7.0

**Comment by ZacharyKhan** [comment]
Please resubmit your issue following our template:

https://github.com/ra1028/Former/issues/new?template=bug_report.md
