### ISSUE TITLE
pod update

### ISSUE THREAD

**Issue by vitobellini** [ra1028/Former#86]
Please, push the new 1.7 version to the cocoapods repo

**Comment by ZacharyKhan** [comment]
Version `0.1.8` has been released and is the latest version. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by vitobellini** [comment]
I see the 1.6.1 version on cocoa pods repo

https://cocoapods.org/pods/Former <https://cocoapods.org/pods/Former>

**Comment by suleymancalik** [comment]
There is an important bug fix after version 1.7.  Please push a new version. Thanks.

**Comment by ZacharyKhan** [comment]
@ra1028

**Comment by ZacharyKhan** [comment]
@ra1028 Can you update the podfile?

**Comment by ZacharyKhan** [comment]
Ryo emailed me - he will transfer the CocoaPod over to me and I will update to V1.8.0 to include all of the latest updates.
