### ISSUE TITLE
Clear button for dates

### ISSUE THREAD

**Issue by walsht** [ra1028/Former#90]
I need a way to clear the date once selected. 
Button on the InlineDatePickerRowFormer cell to clear the date will work.

**Comment by ZacharyKhan** [comment]
As mentioned in my comment to your other issue, I am closing this in an effort to keep the focus on bugs within the library. There's not enough context here to help you. 

If you would like to post a code snippet and create a new issue following the template, I'd be happy to help.

https://github.com/ra1028/Former/issues/new?template=bug_report.md
