### ISSUE TITLE
No way to format text with TextFieldRowFormer 

### ISSUE THREAD

**Issue by walsht** [ra1028/Former#91]
No way to format text with TextFieldRowFormer. You have something for date/slider/step but would like to be able to have the user input a number and format it to currency.

**Comment by Daxito** [comment]
CustomRowFormer allows you to add any UITableViewCell with any content, maybe that can help.

**Comment by ZacharyKhan** [comment]
Hi Tim,

As David mentioned, your best bet is to create a custom cell and use this instead. The default cells are really meant to be used in simple cases or as references when building your own. I'm closing this issue in an effort to focus on actual bugs within the library as there are less and less people maintaining this library.
