### ISSUE TITLE
Please add validation data 

### ISSUE THREAD

**Issue by purnachandarr** [ra1028/Former#95]
Please add validation all the filed getting expected data fielding or not.

Please add validation all the filed getting expected data fielding or not and once all the rows complete with the information give a complete status.

**Comment by ZacharyKhan** [comment]
Can you please explain what you are needing?

**Comment by ZacharyKhan** [comment]
@purnachandarr I am closing this issue in an effort to clean up the issues page. 

If you’re issue persists, please follow the guidelines in the README and submit a new issue using the template provided via the link.
